table fatAConteudo
	lineageTag: 983274ab-db62-4ca7-9eb6-e30a71960044

	column Exibição
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7ad230fb-9d28-4596-96ab-71f785ca7c60
		summarizeBy: none
		sourceColumn: Exibição

		variation Variation
			isDefault
			relationship: c164ea72-8259-4274-8067-82aa6e4d46cc
			defaultHierarchy: LocalDateTable_0ed2c133-099d-4aa4-acdb-eb0d515e8663.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Cliente
		dataType: string
		lineageTag: 30339fd4-e9b4-4fe3-beb8-372e9a2ebdfa
		summarizeBy: none
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: 9aaa6343-d3c9-4a7d-a4a8-ec1092735411
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column Origem
		dataType: string
		lineageTag: b437b059-ac3d-4340-92e3-82ac1cf61230
		summarizeBy: none
		sourceColumn: Origem

		annotation SummarizationSetBy = Automatic

	column Vendedor
		dataType: string
		lineageTag: eab6d8b6-3691-4fc4-9bf6-5767cb988972
		summarizeBy: none
		sourceColumn: Vendedor

		annotation SummarizationSetBy = Automatic

	column 'Conteúdo Bruto'
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: ab4028a3-5e3e-4a39-b86b-175fda7c4ebf
		summarizeBy: sum
		sourceColumn: Conteúdo Bruto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column DeC
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: b3be800f-8dcc-43eb-ac5f-ae1985447d9a
		summarizeBy: sum
		sourceColumn: DeC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Produção Plano'
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 44b8bd12-5a4f-4298-bf8c-035a4ea9fd57
		summarizeBy: sum
		sourceColumn: Produção Plano

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Produção Real'
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 44abcaaa-197b-42a2-ba80-e37d190461ff
		summarizeBy: sum
		sourceColumn: Produção Real

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Desconto
		dataType: double
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 3eee231a-99b7-45d4-b04f-61cff8b31d49
		summarizeBy: sum
		sourceColumn: Desconto

		annotation SummarizationSetBy = Automatic

	column 'Conteudo Bruto Negociado'
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 3e3d22cc-d42c-4523-83f4-d064273de973
		summarizeBy: sum
		sourceColumn: Conteudo Bruto Negociado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Agência
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: df10dddd-5bb3-4b6b-a355-1194217e1130
		summarizeBy: sum
		sourceColumn: Agência

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Conteúdo Líquido'
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 485cd96f-96d0-4620-938c-9268f91a6a5c
		summarizeBy: sum
		sourceColumn: Conteúdo Líquido

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Programa
		dataType: string
		lineageTag: a18365a2-bef5-4d07-bc90-fd95a48f9963
		summarizeBy: none
		sourceColumn: Programa

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: string
		lineageTag: 742ff959-24b8-4220-bf97-4b5712e5a96b
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column PRAÇA
		dataType: string
		lineageTag: b3d6e29b-0162-4425-a3c0-4065ee25c6cd
		summarizeBy: none
		sourceColumn: PRAÇA

		annotation SummarizationSetBy = Automatic

	column Prog
		dataType: string
		lineageTag: 6fdbceb5-17c0-411a-9221-c5a671d5bddf
		summarizeBy: none
		sourceColumn: Prog

		annotation SummarizationSetBy = Automatic

	column Apresentador
		dataType: string
		lineageTag: 30637721-2ad9-4d08-845c-126237a3e6f6
		summarizeBy: none
		sourceColumn: Apresentador

		annotation SummarizationSetBy = Automatic

	column Vinheta
		dataType: string
		lineageTag: b53041d8-3524-4048-b852-0ce9e0817642
		summarizeBy: none
		sourceColumn: Vinheta

		annotation SummarizationSetBy = Automatic

	column 'Comissão Apresentação'
		dataType: double
		lineageTag: 2027307f-4761-4200-9a67-62929fe9128b
		summarizeBy: sum
		sourceColumn: Comissão Apresentação

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Produto
		dataType: string
		lineageTag: ea6b0d13-01e3-4616-8f87-24b242558214
		summarizeBy: none
		sourceColumn: Produto

		annotation SummarizationSetBy = Automatic

	column 'Cachê Apresentador'
		dataType: double
		lineageTag: e983fa74-1330-44a7-9922-c84d8fdc2a3c
		summarizeBy: sum
		sourceColumn: Cachê Apresentador

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cobertura
		dataType: string
		lineageTag: ffd5cd80-0f90-4635-9e89-bf41cb00a531
		summarizeBy: none
		sourceColumn: Cobertura

		annotation SummarizationSetBy = Automatic

	column 'Líquido Faturado'
		dataType: double
		lineageTag: 8a277e98-5919-4168-9cec-23b524744bb1
		summarizeBy: sum
		sourceColumn: Líquido Faturado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fatAConteudo = m
		mode: import
		source = ```
				let 
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1_qe6fIK09GaZOuUAheZzRM3uhBGJeHtPBufEy8LZmy4/edit?gid=553044125#gid=553044125"), 
				    #"Filtered Rows2" = Table.SelectRows(Source, each ([name] <> "RESUMO")), 
				    #"Expanded Data" = Table.ExpandTableColumn(#"Filtered Rows2", "Data", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24"}, {"Data.Column1", "Data.Column2", "Data.Column3", "Data.Column4", "Data.Column5", "Data.Column6", "Data.Column7", "Data.Column8", "Data.Column9", "Data.Column10", "Data.Column11", "Data.Column12", "Data.Column13", "Data.Column14", "Data.Column15", "Data.Column16", "Data.Column17", "Data.Column18", "Data.Column19", "Data.Column20", "Data.Column21","Column22", "Column23", "Column24"}), 
				    #"Promoted Headers3" = Table.PromoteHeaders(#"Expanded Data", [PromoteAllScalars=true]), 
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Promoted Headers3", [PromoteAllScalars=true]), 
				    #"Promoted Headers2" = Table.PromoteHeaders(#"Promoted Headers1", [PromoteAllScalars=true]),
				    #"Filtered Rows1" = Table.SelectRows(#"Promoted Headers2", each ([ORIGEM] = "GLOBO" or [ORIGEM] = "LOCAL")), 
				    #"Linhas Válidas" = Table.SelectRows(#"Filtered Rows1", each 
				        try Date.From([EXIBIÇÃO]) is date otherwise false 
				    ),
				    
				    /* 🔧 AJUSTE AQUI — DAQUI case/space safe */ 
				    #"Colunas Renomeadas" = 
				        Table.TransformColumnNames( 
				            #"Linhas Válidas", 
				            each if Text.Upper(Text.Trim(_)) = "DAQUI" then "GE" else _ 
				            ), 
				
				    #"Duplicated Column" = Table.DuplicateColumn(#"Colunas Renomeadas", "GE", "GE - Copy"), 
				
				    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"GE - Copy", "Prog"}}), 
				
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns","PGMS ESP","",Replacer.ReplaceText,{"GE"}), 
				
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value",{{"PROGRAMA", type text}}), 
				
				    #"Merged Columns" = Table.CombineColumns(#"Changed Type",{"GE", "PROGRAMA"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Programa"), 
				    
				    #"Removed Other Columns" = Table.SelectColumns(#"Merged Columns",{"EXIBIÇÃO", "Programa", "CLIENTE", "APRESENTADOR", "PRODUTO/CAMPANHA", "TIPO DE AÇÃO", "COBERTURA", "ORIGEM", "PRAÇA", "VENDEDOR", "R$ CONTEÚDO BRUTO", "DESCONTO (%)", "R$ CONTEÚDO BRUTO NEGOCIADO", "VINHETA", "R$ AGÊNCIA (20%)", "R$ CONTEÚDO LÍQUIDO", "DIREITOS E CONEXOS (15%)", "CACHÊ APRESENTADOR", "R$ PRODUÇÃO NO PLANO", "R$ PRODUÇÃO REAL", "COMISSÃO APRESENTADOR", "VALOR LIQ FATURADO", "Prog"}), 
				    
				    #"Changed Type3" = Table.TransformColumnTypes(#"Removed Other Columns",{{"EXIBIÇÃO", type text}, {"Programa", type text}, {"CLIENTE", type text}, {"PRODUTO/CAMPANHA", type text}, {"TIPO DE AÇÃO", type text}, {"COBERTURA", type text}, {"ORIGEM", type text}, {"VENDEDOR", type text}, {"R$ CONTEÚDO BRUTO", type number}, {"DESCONTO (%)", type number}, {"R$ CONTEÚDO BRUTO NEGOCIADO", type number}, {"R$ AGÊNCIA (20%)", type number}, {"R$ CONTEÚDO LÍQUIDO", type number}, {"DIREITOS E CONEXOS (15%)", type number}, {"CACHÊ APRESENTADOR", type number}, {"R$ PRODUÇÃO NO PLANO", type number}, {"R$ PRODUÇÃO REAL", type number}, {"COMISSÃO APRESENTADOR", type number}, {"VALOR LIQ FATURADO", type number}}), 
				    
				    #"Replaced Value1" = Table.ReplaceValue(#"Changed Type3","A DEFINIR","",Replacer.ReplaceText,{"EXIBIÇÃO"}), 
				    
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value1",{{"EXIBIÇÃO", type date}}), 
				    
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type1",{{"EXIBIÇÃO", "Exibição"}, {"CLIENTE", "Cliente"}, {"PRODUTO/CAMPANHA", "Produto"}, {"TIPO DE AÇÃO", "Tipo"}, {"COBERTURA", "Cobertura"}, {"ORIGEM", "Origem"}, {"VENDEDOR", "Vendedor"}, {"R$ CONTEÚDO BRUTO", "Conteúdo Bruto"}, {"DESCONTO (%)", "Desconto"}, {"R$ CONTEÚDO BRUTO NEGOCIADO", "Conteudo Bruto Negociado"}, {"R$ AGÊNCIA (20%)", "Agência"}, {"R$ CONTEÚDO LÍQUIDO", "Conteúdo Líquido"}, {"DIREITOS E CONEXOS (15%)", "DeC"}, {"CACHÊ APRESENTADOR", "Cachê Apresentador"}, {"R$ PRODUÇÃO NO PLANO", "Produção Plano"}, {"R$ PRODUÇÃO REAL", "Produção Real"}, {"COMISSÃO APRESENTADOR", "Comissão Apresentação"}, {"VALOR LIQ FATURADO", "Líquido Faturado"}, {"VINHETA", "Vinheta"}, {"APRESENTADOR", "Apresentador"}}), 
				    
				    #"Added Index" = Table.AddIndexColumn(#"Renamed Columns1", "Index", 1, 1, Int64.Type), 
				    
				    #"Changed Type4" = Table.TransformColumnTypes(#"Added Index",{{"Index", type text}, {"Prog", type text}, {"PRAÇA", type text}})
				in
				    #"Changed Type4"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

